const card = {
    basic: [
        { name: "1", is_active: false, is_bingo: false },
        { name: "2", is_active: false, is_bingo: false },
        { name: "3", is_active: false, is_bingo: false },
        { name: "4", is_active: false, is_bingo: false },
        { name: "5", is_active: false, is_bingo: false },
        { name: "6", is_active: false, is_bingo: false },
        { name: "7", is_active: false, is_bingo: false },
        { name: "8", is_active: false, is_bingo: false },
        { name: "9", is_active: false, is_bingo: false },
        { name: "10", is_active: false, is_bingo: false },
        { name: "11", is_active: false, is_bingo: false },
        { name: "12", is_active: false, is_bingo: false },
        { name: "13", is_active: false, is_bingo: false },
        { name: "14", is_active: false, is_bingo: false },
        { name: "15", is_active: false, is_bingo: false },
        { name: "16", is_active: false, is_bingo: false },
        { name: "17", is_active: false, is_bingo: false },
        { name: "18", is_active: false, is_bingo: false },
        { name: "19", is_active: false, is_bingo: false },
        { name: "20", is_active: false, is_bingo: false },
        { name: "21", is_active: false, is_bingo: false },
        { name: "22", is_active: false, is_bingo: false },
        { name: "24", is_active: false, is_bingo: false },
        { name: "23", is_active: false, is_bingo: false },
    ],
    
    conversation: [
        { name: "(child noises in the background)", is_active: false, is_bingo: false },
        { name: "Hello, hello!", is_active: false, is_bingo: false },
        { name: "i need to jump in another call", is_active: false, is_bingo: false },
        { name: "can everyone go on mute", is_active: false, is_bingo: false },
        { name: "could you please get closer to the mic", is_active: false, is_bingo: false },
        { name: "(load painful echo / feedback)", is_active: false, is_bingo: false },
        { name: "Next slide, please", is_active: false, is_bingo: false },
        { name: "can we take this offline?", is_active: false, is_bingo: false },
        { name: "is ___ on the call?", is_active: false, is_bingo: false },
        { name: "Could you share this slide afterwards", is_active: false, is_bingo: false },
        { name: "can somebody grant presenter rights?", is_active: false, is_bingo: false },
        { name: "can you email that to everyone?", is_active: false, is_bingo: false },
        { name: "sorry, i had problems loging in", is_active: false, is_bingo: false },
        { name: "(animal noises in the background)", is_active: false, is_bingo: false },
        { name: "sorry, i didn\'t found the conference id", is_active: false, is_bingo: false },
        { name: "i was having connection issues", is_active: false, is_bingo: false },
        { name: "i\'ll have to get back to you", is_active: false, is_bingo: false },
        { name: "who just joined?", is_active: false, is_bingo: false },
        { name: "sorry, something with my calender", is_active: false, is_bingo: false },
        { name: "do you see my screen?", is_active: false, is_bingo: false },
        { name: "let\'s wait for ___ !", is_active: false, is_bingo: false },
        { name: "You will send the minutes?", is_active: false, is_bingo: false },
        { name: "sorry, i was on mute", is_active: false, is_bingo: false },
        { name: "can you repeat, please?", is_active: false, is_bingo: false },
    ],
};

export default card;
