const card = {
    basic: [
        { name: "1", isActive: false, isBingo: false },
        { name: "2", isActive: false, isBingo: false },
        { name: "3", isActive: false, isBingo: false },
        { name: "4", isActive: false, isBingo: false },
        { name: "5", isActive: false, isBingo: false },
        { name: "6", isActive: false, isBingo: false },
        { name: "7", isActive: false, isBingo: false },
        { name: "8", isActive: false, isBingo: false },
        { name: "9", isActive: false, isBingo: false },
        { name: "10", isActive: false, isBingo: false },
        { name: "11", isActive: false, isBingo: false },
        { name: "12", isActive: false, isBingo: false },
        { name: "13", isActive: false, isBingo: false },
        { name: "14", isActive: false, isBingo: false },
        { name: "15", isActive: false, isBingo: false },
        { name: "16", isActive: false, isBingo: false },
        { name: "17", isActive: false, isBingo: false },
        { name: "18", isActive: false, isBingo: false },
        { name: "19", isActive: false, isBingo: false },
        { name: "20", isActive: false, isBingo: false },
        { name: "21", isActive: false, isBingo: false },
        { name: "22", isActive: false, isBingo: false },
        { name: "24", isActive: false, isBingo: false },
        { name: "23", isActive: false, isBingo: false },
    ],
    
    conversation: [
        { name: "(child noises in the background)", isActive: false, isBingo: false },
        { name: "Hello, hello!", isActive: false, isBingo: false },
        { name: "i need to jump in another call", isActive: false, isBingo: false },
        { name: "can everyone go on mute", isActive: false, isBingo: false },
        { name: "could you please get closer to the mic", isActive: false, isBingo: false },
        { name: "(load painful echo / feedback)", isActive: false, isBingo: false },
        { name: "Next slide, please", isActive: false, isBingo: false },
        { name: "can we take this offline?", isActive: false, isBingo: false },
        { name: "is ___ on the call?", isActive: false, isBingo: false },
        { name: "Could you share this slide afterwards", isActive: false, isBingo: false },
        { name: "can somebody grant presenter rights?", isActive: false, isBingo: false },
        { name: "can you email that to everyone?", isActive: false, isBingo: false },
        { name: "sorry, i had problems loging in", isActive: false, isBingo: false },
        { name: "(animal noises in the background)", isActive: false, isBingo: false },
        { name: "sorry, i didn\'t found the conference id", isActive: false, isBingo: false },
        { name: "i was having connection issues", isActive: false, isBingo: false },
        { name: "i\'ll have to get back to you", isActive: false, isBingo: false },
        { name: "who just joined?", isActive: false, isBingo: false },
        { name: "sorry, something with my calender", isActive: false, isBingo: false },
        { name: "do you see my screen?", isActive: false, isBingo: false },
        { name: "let\'s wait for ___ !", isActive: false, isBingo: false },
        { name: "You will send the minutes?", isActive: false, isBingo: false },
        { name: "sorry, i was on mute", isActive: false, isBingo: false },
        { name: "can you repeat, please?", isActive: false, isBingo: false },
    ],
};

export default card;
